version: '3.8'
services:

  node:
    image: node:16
    container_name: case-xp-front
    tty: true
    stdin_open: true
    command: bash
    restart: always
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - 3000:3000
    environment:
      REACT_APP_BACK_ENV: case-xp-back-end-development

networks:
  default:
    name: case-xp
